### ISSUE TITLE
OAuth permissions?

### ISSUE THREAD

**Issue by lukaszkorecki** [andreausu/github-notifier#1]
This project looks really nice - one question though, I'm assuming that it doesn't need "write" permissions just to monitor activity in my account, right?

![](https://www.dropbox.com/s/cirh8796uzmf66e/Screenshot%202015-02-23%2012.24.03.png?dl=1)

Looks quite scary when authorising  to be honest

**Comment by andreausu** [comment]
You're totally right, I will fix it as soon as I get off my main job, thanks!

**Comment by lukaszkorecki** [comment]
Great, thanks!

**Comment by andreausu** [comment]
The fix is live :)

**Comment by lukaszkorecki** [comment]
:+1: Awesome
