### ISSUE TITLE
Question: why does it need access to notifications?

### ISSUE THREAD

**Issue by chocolateboy** [andreausu/github-notifier#3]
Looking forward to using this, but I'm puzzled by the new **notifications** permission.

According to the [GitHub help page](https://help.github.com/articles/connecting-with-third-party-applications/#notifications):

>  Notification access allows applications to read your GitHub notifications, such as comments on issues and pull requests.

GitHub notifies you of these already (by default), and they don't appear to have anything to do with any of the events the application monitors, and I can't see any changes in [the commit that introduces them](https://github.com/andreausu/github-notifier/commit/d36161226f40a8420fed8ed534bb4544065fc278) which use this new permission. Why is it needed?

**Comment by andreausu** [comment]
You are right, it's not really needed and should be removed.
If you want you can submit a PR, otherwise I will fix it as soon as I have some time :)

**Comment by chocolateboy** [comment]
> If you want you can submit a PR

[Done](https://github.com/andreausu/github-notifier/pull/4) :-)

**Comment by andreausu** [comment]
Merged and deployed, thanks :)
